# config/services.yml
dev:
  parameters:

all:
  parameters:

  services:
    dummy:
      abstract: true
    manifestations_service:
      class: ManifestationsService
    member_cards_service:
      class: MemberCardsService
    member_card_seating_service:
      class: MemberCardSeatingService
    member_cards_seating_service:
      class: MemberCardsSeatingService
      calls:
        - ['setMemberCardSeatingService', ['@member_card_seating_service']]
    app_country_service:
      class: CountryService
    pub_service:
      class: PubService
    password_plain_text_service:
      class: PasswordPlainTextService
    password_md5_service:
      class: PasswordMD5Service
    ticket_service:
      class: TicketService
